name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: install
      run: yarn install

    # - name: test
    #   run: npm test

    - name: generate
      run: yarn run generate

    - name: deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist